#!/usr/bin/perl

#
# Interpreter for the "99" programming language.
#

use strict;
use warnings;

#
# Check for errors.
#
/^\s*(#.*)?$/ or die $ARGV eq '-' ? 'stdin' : $ARGV, ":$.: Syntax error\n" while (<>);

#
# "Run" the "program".
#
for (reverse 0..99) {
    my $__  = $_; $__--;
    my $s   = $__ ? 's'   : '';
    my $num = $_  ? $_    : 'No';
    my $one = $__ ? 'one' : 'it';
    my $bottles = "$num bottle$s of beer";
    my $take = "Take $one down, pass it around";
    print "$bottles on the wall.\n" if $_ < 99;
    print "\n" if $_ % 99;
    print "$bottles on the wall,\n$bottles.\n$take,\n" if $_;
}
