#!/usr/bin/perl

#
# Interpreter for the "99" programming language.
#

use strict;
use warnings;

#
# Check for errors.
#
/^\s*(#.*)?$/ or die $ARGV eq '-' ? 'stdin' : $ARGV, ":$.: Syntax error\n" while (<>);

#
# "Run" the "program".
#
for (reverse 0..99) {
    my $__ = $_; $__--;
    my $s  = $__ ? 's'   : '';
    my $n  = $_  ? $_    : 'No';
    my $o  = $__ ? 'one' : 'it';
    my $b  = "$n bottle$s of beer";
    my $t  = "Take $o down, pass it around";
    print "$b on the wall.\n" if $_ < 99;
    print "\n" if $_ % 99;
    print "$b on the wall,\n$b.\n$t,\n" if $_;
}
